### ISSUE TITLE
Setting not working: "CreateNewFiles.finalClass": true

### ISSUE THREAD

**Issue by still-dreaming-1** [i74ifa/vscode-create-files#1]
Hello.  Here are my settings:
```
   "CreateNewFiles.finalClass": true,
   "CreateNewFiles.strictTypes": true,
```
When I create a new php class, everything is correct except the class is not final. The file name is correct, the namespace is correct, it does use strict_types, and the class name is correct. But for some reason the class is not final.

**Comment by still-dreaming-1** [comment]
I'm interested in trying to create a PR for this, but I'm not familiar with VSCode plugin development. Can you give me any tips for building and testing after I make changes?

**Comment by i74ifa** [comment]
This option hasn't been considered yet. The problem is that I have created a template for each type of file types, and I'm unsure whether to create a template for the final class or just add a slot in the class template.

**Comment by i74ifa** [comment]
[i fixed v.1.1.2](https://github.com/i74ifa/vscode-create-files/commit/65b42a50098b8dccca28a1b94161974560febe46)

thank you .
