### ISSUE TITLE
Bug: Extra space in default template for php interface and enum

### ISSUE THREAD

**Issue by still-dreaming-1** [i74ifa/vscode-create-files#5]
I fixed this in a [pull request](https://github.com/i74ifa/vscode-create-files/pull/3) that has already been accepted. However it is still broken in the current version because there has not been a new release since then. Can you please do a new release?

**Comment by i74ifa** [comment]
Oh sorry, I was busy and didn't pay attention to this

I was busy and didn't pay attention to this [v1.1.6](https://github.com/i74ifa/vscode-create-files/commit/3a699cdbcde9d4c964ba364a534fc9036465157d)

Finally, I have made you a contributor to this repo. I hope you will accept the invitation
